import { useRef, useState } from 'react';
import { useInterfaceCrud } from '../../../standard-api-testing/hooks/useInterfaceCrud';
import { useInterfaceEditor } from '../../../standard-api-testing/hooks/useInterfaceEditor';
import { translateError } from '../../../standard-api-testing/utils/requestUi';
import type { SavedInterface, StandardAPITestingProps } from '../../../standard-api-testing/utils/types';
import { useApiTestingEnvironment } from './useApiTestingEnvironment';
import { useApiTestingInterfaceTree } from './useApiTestingInterfaceTree';
import { useApiTestingLayout } from './useApiTestingLayout';
import { useApiTestingRequest } from './useApiTestingRequest';

export function useStandardApiTestingController({ projectId, onLog }: StandardAPITestingProps) {
  const [apiPath, setApiPath] = useState('');
  const [showCookieModal, setShowCookieModal] = useState(false);
  const [cookieJar, setCookieJar] = useState<Record<string, string>>({});

  const [savedInterfaces, setSavedInterfaces] = useState<SavedInterface[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [draggedId, setDraggedId] = useState<number | null>(null);
  const [dragOverId, setDragOverId] = useState<number | null>(null);
  const [dragOverPosition, setDragOverPosition] = useState<'top' | 'bottom' | 'middle' | null>(null);
  const [hoverId, setHoverId] = useState<number | null>(null);
  const [bulkDeleteMode, setBulkDeleteMode] = useState(false);
  const [bulkSelected, setBulkSelected] = useState<Record<number, boolean>>({});
  const [renamingId, setRenamingId] = useState<number | null>(null);
  const [renamingName, setRenamingName] = useState('');

  const inputRef = useRef<HTMLInputElement>(null);
  const highlighterRef = useRef<HTMLDivElement>(null);

  const layout = useApiTestingLayout();
  const environment = useApiTestingEnvironment({ apiPath, inputRef });
  const request: any = useApiTestingRequest({
    projectId,
    onLog,
    apiPath,
    savedEnvs: environment.savedEnvs,
    setSavedEnvs: environment.setSavedEnvs,
    getEnvBaseUrlValue: environment.getEnvBaseUrlValue,
    cookieJar,
    setCookieJar,
  });

  const { fetchInterfaces, createFolder, createInterface, updateInterface } = useInterfaceCrud({
    projectId,
    selectedId,
    savedInterfaces,
    setSavedInterfaces,
    apiPath,
    method: request.method,
    queryParams: request.queryParams,
    headers: request.headers,
    bodyMode: request.bodyMode,
    rawType: request.rawType,
    bodyContent: request.bodyContent,
    translateError,
  });

  const {
    showSaveModal,
    setShowSaveModal,
    saveForm,
    setSaveForm,
    handleEditFolder,
    handleSaveInterfaceClick,
    handleConfirmSave,
    handleLoadInterface,
    renderFolderOptions,
  } = useInterfaceEditor({
    projectId,
    savedInterfaces,
    setSavedInterfaces,
    selectedId,
    setSelectedId,
    apiPath,
    setApiPath,
    method: request.method,
    setMethod: request.setMethod,
    requirement: request.requirement,
    setRequirement: request.setRequirement,
    mode: request.mode,
    setMode: request.setMode,
    testTypes: request.testTypes,
    setTestTypes: request.setTestTypes,
    headers: request.headers,
    setHeaders: request.setHeaders,
    queryParams: request.queryParams,
    setQueryParams: request.setQueryParams,
    bodyMode: request.bodyMode,
    setBodyMode: request.setBodyMode,
    rawType: request.rawType,
    setRawType: request.setRawType,
    bodyContent: request.bodyContent,
    setBodyContent: request.setBodyContent,
    preRequestScript: request.preRequestScript,
    setPreRequestScript: request.setPreRequestScript,
    postResponseScript: request.postResponseScript,
    setPostResponseScript: request.setPostResponseScript,
    setResponseStatus: request.setResponseStatus,
    setResponseTime: request.setResponseTime,
    setResponseBody: request.setResponseBody,
    setResponseHeaders: request.setResponseHeaders,
    setResponseCookies: request.setResponseCookies,
    setTestResult: request.setTestResult,
    updateInterface,
    fetchInterfaces,
    translateError,
    onLog,
  });

  const tree = useApiTestingInterfaceTree({
    savedInterfaces,
    setSavedInterfaces,
    selectedId,
    setSelectedId,
    draggedId,
    setDraggedId,
    dragOverId,
    setDragOverId,
    dragOverPosition,
    setDragOverPosition,
    hoverId,
    setHoverId,
    bulkDeleteMode,
    setBulkDeleteMode,
    bulkSelected,
    setBulkSelected,
    renamingId,
    setRenamingId,
    renamingName,
    setRenamingName,
    projectId,
    fetchInterfaces,
    createFolder,
    createInterface,
    updateInterface,
    handleLoadInterface,
    translateError,
    onLog,
  });

  return {
    mode: request.mode,
    setMode: request.setMode,
    requirement: request.requirement,
    setRequirement: request.setRequirement,
    apiPath,
    setApiPath,
    method: request.method,
    setMethod: request.setMethod,
    testTypes: request.testTypes,
    setTestTypes: request.setTestTypes,
    loading: request.loading,
    testResult: request.testResult,
    responseStatus: request.responseStatus,
    responseTime: request.responseTime,
    responseBody: request.responseBody,
    responseHeaders: request.responseHeaders,
    responseCookies: request.responseCookies,
    responseDetailedCookies: request.responseDetailedCookies,
    sentHeaders: request.sentHeaders,
    sentCookies: request.sentCookies,
    sentBody: request.sentBody,
    scriptTests: request.scriptTests,
    responseViewMode: request.responseViewMode,
    setResponseViewMode: request.setResponseViewMode,
    responseFormat: request.responseFormat,
    setResponseFormat: request.setResponseFormat,
    aiAnalysis: request.aiAnalysis,
    isAnalyzing: request.isAnalyzing,
    showEnvModal: environment.showEnvModal,
    setShowEnvModal: environment.setShowEnvModal,
    showCookieModal,
    setShowCookieModal,
    cookieJar,
    setCookieJar,
    editingEnv: environment.editingEnv,
    setEditingEnv: environment.setEditingEnv,
    renamingId: tree.renamingId,
    setRenamingId: tree.setRenamingId,
    renamingName: tree.renamingName,
    setRenamingName: tree.setRenamingName,
    showSidebar: layout.showSidebar,
    setShowSidebar: layout.setShowSidebar,
    sidebarWidth: layout.sidebarWidth,
    isResizingSidebar: layout.isResizingSidebar,
    requestHeight: layout.requestHeight,
    isDragging: layout.isDragging,
    handleRequestBarMouseDown: layout.handleRequestBarMouseDown,
    handleSidebarResizerMouseDown: layout.handleSidebarResizerMouseDown,
    mainContentRef: layout.mainContentRef,
    inputRef,
    highlighterRef,
    savedEnvs: environment.savedEnvs,
    handleDeleteEnv: environment.handleDeleteEnv,
    handleUpdateEnv: environment.handleUpdateEnv,
    activeEnvTag: environment.activeEnvTag,
    showPopup: environment.showPopup,
    setShowPopup: environment.setShowPopup,
    getEnvBaseUrlValue: environment.getEnvBaseUrlValue,
    setEnvBaseUrlValue: environment.setEnvBaseUrlValue,
    handleApiPathBlur: environment.handleApiPathBlur,
    handleInputMouseMove: environment.handleInputMouseMove,
    handleInputMouseLeave: environment.handleInputMouseLeave,
    handlePopupMouseEnter: environment.handlePopupMouseEnter,
    handlePopupMouseLeave: environment.handlePopupMouseLeave,
    runSubTab: request.runSubTab,
    setRunSubTab: request.setRunSubTab,
    queryParams: request.queryParams,
    setQueryParams: request.setQueryParams,
    headers: request.headers,
    setHeaders: request.setHeaders,
    authType: request.authType,
    setAuthType: request.setAuthType,
    authToken: request.authToken,
    setAuthToken: request.setAuthToken,
    authBasic: request.authBasic,
    setAuthBasic: request.setAuthBasic,
    authApiKey: request.authApiKey,
    setAuthApiKey: request.setAuthApiKey,
    activeScriptTab: request.activeScriptTab,
    setActiveScriptTab: request.setActiveScriptTab,
    preRequestScript: request.preRequestScript,
    setPreRequestScript: request.setPreRequestScript,
    postResponseScript: request.postResponseScript,
    setPostResponseScript: request.setPostResponseScript,
    requestSettings: request.requestSettings,
    setRequestSettings: request.setRequestSettings,
    bodyMode: request.bodyMode,
    setBodyMode: request.setBodyMode,
    rawType: request.rawType,
    setRawType: request.setRawType,
    bodyContent: request.bodyContent,
    setBodyContent: request.setBodyContent,
    formDataParams: request.formDataParams,
    setFormDataParams: request.setFormDataParams,
    xWwwFormUrlencodedParams: request.xWwwFormUrlencodedParams,
    setXWwwFormUrlencodedParams: request.setXWwwFormUrlencodedParams,
    binaryFile: request.binaryFile,
    setBinaryFile: request.setBinaryFile,
    graphqlQuery: request.graphqlQuery,
    setGraphqlQuery: request.setGraphqlQuery,
    graphqlVariables: request.graphqlVariables,
    setGraphqlVariables: request.setGraphqlVariables,
    isBulkEditFormData: request.isBulkEditFormData,
    setIsBulkEditFormData: request.setIsBulkEditFormData,
    formDataBulkText: request.formDataBulkText,
    setFormDataBulkText: request.setFormDataBulkText,
    isBulkEditBody: request.isBulkEditBody,
    setIsBulkEditBody: request.setIsBulkEditBody,
    bodyBulkText: request.bodyBulkText,
    setBodyBulkText: request.setBodyBulkText,
    isBulkEditParams: request.isBulkEditParams,
    setIsBulkEditParams: request.setIsBulkEditParams,
    paramsBulkText: request.paramsBulkText,
    setParamsBulkText: request.setParamsBulkText,
    isBulkEditHeaders: request.isBulkEditHeaders,
    setIsBulkEditHeaders: request.setIsBulkEditHeaders,
    headersBulkText: request.headersBulkText,
    setHeadersBulkText: request.setHeadersBulkText,
    bodyHighlighterRef: request.bodyHighlighterRef,
    handleBodyScroll: request.handleBodyScroll,
    responseTab: request.responseTab,
    setResponseTab: request.setResponseTab,
    handleSendRequest: request.handleSendRequest,
    handleSaveInterfaceClick,
    handleSaveEnv: environment.handleSaveEnv,
    handleRun: request.handleRun,
    savedInterfaces,
    selectedId,
    setSelectedId,
    dragOverId,
    dragOverPosition,
    hoverId,
    setHoverId,
    bulkDeleteMode,
    bulkSelected,
    handleDragStart: tree.handleDragStart,
    handleDragOver: tree.handleDragOver,
    handleDragLeave: tree.handleDragLeave,
    handleDrop: tree.handleDrop,
    handleToggleBulkSelected: tree.handleToggleBulkSelected,
    handleLoadInterface,
    toggleFolder: tree.toggleFolder,
    handleCreateFolder: tree.handleCreateFolder,
    handleCreateInterface: tree.handleCreateInterface,
    handleEditFolder,
    handleRenameConfirm: tree.handleRenameConfirm,
    handleDeleteInterface: tree.handleDeleteInterface,
    handleBulkDeleteToggleOrConfirm: tree.handleBulkDeleteToggleOrConfirm,
    fetchInterfaces,
    importFiles: tree.importFiles,
    handleOpenFolderAfterImport: tree.handleOpenFolderAfterImport,
    onOpenCookieManager: () => setShowCookieModal(true),
    showSaveModal,
    setShowSaveModal,
    saveForm,
    setSaveForm,
    renderFolderOptions,
    handleConfirmSave,
    handleAnalyzeResponse: request.handleAnalyzeResponse,
  };
}

