from __future__ import annotations

from typing import Any


def _int_or_zero(value: Any) -> int:
    return int(value or 0)


def build_convergence_count_debug_fields(
    *,
    reference_count_effective: Any = 0,
    final_count: Any = 0,
    reference_gap: Any = 0,
    converged: Any = False,
    duplication_rate_estimate: Any = 0.0,
    stage_counts: dict[str, Any] | None = None,
    candidate_count_before_review: Any = 0,
    review_selected_count: Any = 0,
    post_review_dedup_drop: Any = 0,
    judge_reject_count: Any = 0,
    judge_pending_count: Any = 0,
    judge_pass_count: Any = 0,
    final_input_count: Any = 0,
    final_non_judge_drop_count: Any = 0,
    scenario_duplicate_pruned_count: Any = 0,
    post_review_dedup_reorder_drop_count: Any = 0,
    final_description_dedup_drop: Any = 0,
    total_dedup_drop: Any = 0,
    gap_attempts: Any = 0,
    gap_remaining_after_attempts: Any = 0,
    missing_rules_final: Any = None,
    missing_types_final: Any = None,
) -> dict[str, Any]:
    stage_counts = stage_counts or {}

    return {
        "suggested_count": _int_or_zero(reference_count_effective),
        "final_count": _int_or_zero(final_count),
        "reference_gap": _int_or_zero(reference_gap),
        "converged": bool(converged),
        "duplication_rate_estimate": float(duplication_rate_estimate),
        "primary_count": _int_or_zero(stage_counts.get("primary")),
        "gap_count": _int_or_zero(stage_counts.get("gap")),
        "review_count": _int_or_zero(stage_counts.get("review")),
        "candidate_count_before_review": _int_or_zero(candidate_count_before_review),
        "review_selected_count": _int_or_zero(review_selected_count),
        "post_review_dedup_drop": _int_or_zero(post_review_dedup_drop),
        "judge_reject_count": _int_or_zero(judge_reject_count),
        "judge_pending_count": _int_or_zero(judge_pending_count),
        "judge_pass_count": _int_or_zero(judge_pass_count),
        "final_input_count": _int_or_zero(final_input_count),
        "final_output_count": _int_or_zero(final_count),
        "final_non_judge_drop_count": _int_or_zero(final_non_judge_drop_count),
        "scenario_duplicate_pruned_count": _int_or_zero(scenario_duplicate_pruned_count),
        "post_review_dedup_reorder_drop_count": _int_or_zero(post_review_dedup_reorder_drop_count),
        "final_description_dedup_drop_count": _int_or_zero(final_description_dedup_drop),
        "total_dedup_drop_count": _int_or_zero(total_dedup_drop),
        "gap_attempts": _int_or_zero(gap_attempts),
        "gap_remaining_after_attempts": _int_or_zero(gap_remaining_after_attempts),
        "missing_rules_count": int(len(missing_rules_final or [])),
        "missing_types_exists": bool(missing_types_final),
    }


def build_convergence_pruning_debug_fields(
    *,
    effective_low_quality_dropped_total: Any = 0,
    low_quality_drop_details: Any = None,
    postprocess_filter_drop_total: Any = 0,
    semantic_dedup_dropped_total: Any = 0,
    governance_hard_drop_total: Any = 0,
    duplicate_pruned_count: Any = 0,
    invalid_pruned_count: Any = 0,
    quality_rejected_count: Any = 0,
    review_selector_pruned_count: Any = 0,
    valid_unique_candidate_count: Any = 0,
) -> dict[str, Any]:
    return {
        "low_quality_dropped_count": _int_or_zero(effective_low_quality_dropped_total),
        "low_quality_dropped_examples": [
            dict(item)
            for item in (low_quality_drop_details or [])[:10]
            if isinstance(item, dict) and item.get("diagnostic_only") is not True
        ],
        "postprocess_filter_drop_total": _int_or_zero(postprocess_filter_drop_total),
        "semantic_dedup_dropped_count": _int_or_zero(semantic_dedup_dropped_total),
        "governance_hard_drop_count": _int_or_zero(governance_hard_drop_total),
        "duplicate_pruned_count": _int_or_zero(duplicate_pruned_count),
        "invalid_pruned_count": _int_or_zero(invalid_pruned_count),
        "quality_rejected_count": _int_or_zero(quality_rejected_count),
        "review_selector_pruned_count": _int_or_zero(review_selector_pruned_count),
        "valid_unique_candidate_count": _int_or_zero(valid_unique_candidate_count),
    }


def build_convergence_target_debug_fields(
    *,
    generation_coverage_mode: Any = None,
    generation_mode: Any = None,
    effective_generation_coverage_mode_source: Any = None,
    explicit_generation_mode_override: Any = False,
    explicit_expected_count_floor_preserved: Any = False,
    expected_count: Any = 0,
    expected_count_explicit: Any = False,
    target_min: Any = None,
    target_max: Any = None,
    target_final_count: Any = 0,
    soft_min_count: Any = 0,
    hard_min_count: Any = 0,
    min_acceptable_final: Any = 0,
    target_satisfaction_ratio: Any = 0.0,
    underfilled: Any = False,
    underfill_level: Any = "",
    underfill_reason: Any = "",
    underfill_root_cause: Any = "",
    append_target_count: Any = 0,
    append_final_cap_count: Any = 0,
    append_cap_drop_total: Any = 0,
    flow_governance_summary: Any = None,
    needs_priority_review: Any = False,
    priority_conflict_count: Any = 0,
    priority_undetermined_count: Any = 0,
    priority_optional_count: Any = 0,
    reasons: Any = None,
    generation_target_case_range: Any = None,
) -> dict[str, Any]:
    return {
        "generation_coverage_mode": str(generation_coverage_mode or "core_smoke"),
        "requested_generation_mode": str(generation_mode or ""),
        "effective_generation_coverage_mode_source": str(effective_generation_coverage_mode_source or ""),
        "explicit_generation_mode_override": bool(explicit_generation_mode_override),
        "explicit_expected_count_floor_preserved": bool(explicit_expected_count_floor_preserved),
        "expected_count": _int_or_zero(expected_count),
        "expected_count_explicit": bool(expected_count_explicit),
        "recommended_min": _int_or_zero(target_min) if target_min is not None else 0,
        "recommended_max": _int_or_zero(target_max) if target_max is not None else 0,
        "target_final_count": _int_or_zero(target_final_count),
        "soft_min_count": _int_or_zero(soft_min_count),
        "hard_min_count": _int_or_zero(hard_min_count),
        "min_acceptable_final": _int_or_zero(min_acceptable_final),
        "target_satisfaction_ratio": float(target_satisfaction_ratio),
        "underfilled": bool(underfilled),
        "underfill_level": str(underfill_level),
        "underfill_reason": str(underfill_reason),
        "underfill_root_cause": str(underfill_root_cause),
        "append_target_count": _int_or_zero(append_target_count),
        "append_final_cap_count": _int_or_zero(append_final_cap_count),
        "append_cap_drop_count": _int_or_zero(append_cap_drop_total),
        "flow_governance": dict(flow_governance_summary or {}),
        "needs_priority_review": bool(needs_priority_review),
        "priority_conflict_count": int(priority_conflict_count),
        "priority_undetermined_count": int(priority_undetermined_count),
        "priority_optional_count": int(priority_optional_count),
        "reasons": reasons,
        "generation_target_case_range": dict(generation_target_case_range or {}),
    }


def build_convergence_debug(
    *,
    reference_count_effective: Any = 0,
    final_count: Any = 0,
    reference_gap: Any = 0,
    converged: Any = False,
    duplication_rate_estimate: Any = 0.0,
    stage_counts: dict[str, Any] | None = None,
    candidate_count_before_review: Any = 0,
    review_selected_count: Any = 0,
    post_review_dedup_drop: Any = 0,
    judge_reject_count: Any = 0,
    judge_pending_count: Any = 0,
    judge_pass_count: Any = 0,
    final_input_count: Any = 0,
    final_non_judge_drop_count: Any = 0,
    scenario_duplicate_pruned_count: Any = 0,
    post_review_dedup_reorder_drop_count: Any = 0,
    final_description_dedup_drop: Any = 0,
    total_dedup_drop: Any = 0,
    gap_attempts: Any = 0,
    gap_remaining_after_attempts: Any = 0,
    missing_rules_final: Any = None,
    missing_types_final: Any = None,
    effective_low_quality_dropped_total: Any = 0,
    low_quality_drop_details: Any = None,
    postprocess_filter_drop_total: Any = 0,
    semantic_dedup_dropped_total: Any = 0,
    governance_hard_drop_total: Any = 0,
    duplicate_pruned_count: Any = 0,
    invalid_pruned_count: Any = 0,
    quality_rejected_count: Any = 0,
    review_selector_pruned_count: Any = 0,
    valid_unique_candidate_count: Any = 0,
    generation_coverage_mode: Any = None,
    generation_mode: Any = None,
    effective_generation_coverage_mode_source: Any = None,
    explicit_generation_mode_override: Any = False,
    explicit_expected_count_floor_preserved: Any = False,
    expected_count: Any = 0,
    expected_count_explicit: Any = False,
    target_min: Any = None,
    target_max: Any = None,
    target_final_count: Any = 0,
    soft_min_count: Any = 0,
    hard_min_count: Any = 0,
    min_acceptable_final: Any = 0,
    target_satisfaction_ratio: Any = 0.0,
    underfilled: Any = False,
    underfill_level: Any = "",
    underfill_reason: Any = "",
    underfill_root_cause: Any = "",
    append_target_count: Any = 0,
    append_final_cap_count: Any = 0,
    append_cap_drop_total: Any = 0,
    flow_governance_summary: Any = None,
    needs_priority_review: Any = False,
    priority_conflict_count: Any = 0,
    priority_undetermined_count: Any = 0,
    priority_optional_count: Any = 0,
    reasons: Any = None,
    generation_target_case_range: Any = None,
) -> dict[str, Any]:
    return {
        **build_convergence_count_debug_fields(
            reference_count_effective=reference_count_effective,
            final_count=final_count,
            reference_gap=reference_gap,
            converged=converged,
            duplication_rate_estimate=duplication_rate_estimate,
            stage_counts=stage_counts,
            candidate_count_before_review=candidate_count_before_review,
            review_selected_count=review_selected_count,
            post_review_dedup_drop=post_review_dedup_drop,
            judge_reject_count=judge_reject_count,
            judge_pending_count=judge_pending_count,
            judge_pass_count=judge_pass_count,
            final_input_count=final_input_count,
            final_non_judge_drop_count=final_non_judge_drop_count,
            scenario_duplicate_pruned_count=scenario_duplicate_pruned_count,
            post_review_dedup_reorder_drop_count=post_review_dedup_reorder_drop_count,
            final_description_dedup_drop=final_description_dedup_drop,
            total_dedup_drop=total_dedup_drop,
            gap_attempts=gap_attempts,
            gap_remaining_after_attempts=gap_remaining_after_attempts,
            missing_rules_final=missing_rules_final,
            missing_types_final=missing_types_final,
        ),
        **build_convergence_pruning_debug_fields(
            effective_low_quality_dropped_total=effective_low_quality_dropped_total,
            low_quality_drop_details=low_quality_drop_details,
            postprocess_filter_drop_total=postprocess_filter_drop_total,
            semantic_dedup_dropped_total=semantic_dedup_dropped_total,
            governance_hard_drop_total=governance_hard_drop_total,
            duplicate_pruned_count=duplicate_pruned_count,
            invalid_pruned_count=invalid_pruned_count,
            quality_rejected_count=quality_rejected_count,
            review_selector_pruned_count=review_selector_pruned_count,
            valid_unique_candidate_count=valid_unique_candidate_count,
        ),
        **build_convergence_target_debug_fields(
            generation_coverage_mode=generation_coverage_mode,
            generation_mode=generation_mode,
            effective_generation_coverage_mode_source=effective_generation_coverage_mode_source,
            explicit_generation_mode_override=explicit_generation_mode_override,
            explicit_expected_count_floor_preserved=explicit_expected_count_floor_preserved,
            expected_count=expected_count,
            expected_count_explicit=expected_count_explicit,
            target_min=target_min,
            target_max=target_max,
            target_final_count=target_final_count,
            soft_min_count=soft_min_count,
            hard_min_count=hard_min_count,
            min_acceptable_final=min_acceptable_final,
            target_satisfaction_ratio=target_satisfaction_ratio,
            underfilled=underfilled,
            underfill_level=underfill_level,
            underfill_reason=underfill_reason,
            underfill_root_cause=underfill_root_cause,
            append_target_count=append_target_count,
            append_final_cap_count=append_final_cap_count,
            append_cap_drop_total=append_cap_drop_total,
            flow_governance_summary=flow_governance_summary,
            needs_priority_review=needs_priority_review,
            priority_conflict_count=priority_conflict_count,
            priority_undetermined_count=priority_undetermined_count,
            priority_optional_count=priority_optional_count,
            reasons=reasons,
            generation_target_case_range=generation_target_case_range,
        ),
    }


__all__ = [
    "build_convergence_debug",
    "build_convergence_count_debug_fields",
    "build_convergence_pruning_debug_fields",
    "build_convergence_target_debug_fields",
]
