// @ts-nocheck
import{useEffect as P,useMemo as S,useState as n}from"react";import{buildInitialStages as b,defaultAgentConfig as o,runStatusLabel as it,stageOrder as Ae,toText as c}from"./model";import{createPipelineRun as ot,fetchPipelineRun as xe,fetchPipelineTraces as ut,fetchProjectAgentDefaults as lt,listPipelineRuns as ct,resumePipelineRun as gt,retryPipelineRun as pt,updateProjectAgentDefaults as dt}from"./pipelineApi";function y(a){return a&&typeof a=="object"?a:{}}function Pt({projectId:a,onLog:u}){const[_,ve]=n(""),[w,Pe]=n(20),[E,Se]=n(!1),[T,be]=n(""),[M,we]=n("http://localhost:5173"),[C,Ee]=n("web"),[k,Te]=n(""),[U,Me]=n("http://127.0.0.1:8000"),[B,Ce]=n("/api/health"),[O,ke]=n("structured"),[$,Ue]=n(["Functional"]),[L,Be]=n(!1),[D,Oe]=n(!0),[N,$e]=n(!0),[q,Le]=n(""),[H,F]=n(o.enabled),[K,W]=n(o.planner_llm),[V,G]=n(o.reviewer_llm),[z,I]=n(o.executor_parallel),[J,Q]=n(o.executor_workers),[X,Y]=n(o.auto_retry_enabled),[Z,j]=n(o.max_auto_retries),[ee,te]=n(o.retry_policy),[ne,se]=n(o.max_context_chars),[De,l]=n("idle"),[Ne,s]=n(null),[d,ae]=n(b()),[R,re]=n("idle"),[r,ie]=n(null),[qe,He]=n([]),[Fe,oe]=n(!1),[ue,le]=n("test_generation"),[Ke,ce]=n(!1),[A,f]=n([]),[x,v]=n(null),[We,ge]=n(""),[Ve,pe]=n(""),[Ge,de]=n(""),[ze,me]=n(""),[Ie,ye]=n(""),[Je,_e]=n(""),[Qe,fe]=n(""),h=R==="running"||R==="pending",Xe=!!a&&!h&&_.trim().length>0,Ye=S(()=>Ae.map(e=>({key:e,...d[e]})),[d]),Ze=S(()=>A.find(e=>e.id===x)||null,[A,x]),he=S(()=>{for(const e of Ae){const t=d[e]?.status;if(t==="failed"||t==="pending"||t==="idle")return e}return"test_generation"},[d]),je=()=>({enabled:H,planner_llm:K,reviewer_llm:V,executor_parallel:z,executor_workers:Math.max(1,Math.min(8,Number(J)||1)),auto_retry_enabled:X,max_auto_retries:Math.max(0,Math.min(3,Number(Z)||0)),retry_policy:ee,max_context_chars:Math.max(800,Math.min(12e3,Number(ne)||3500))}),et=e=>{F(!!e.enabled),W(!!e.planner_llm),G(!!e.reviewer_llm),I(!!e.executor_parallel),Q(Math.max(1,Math.min(8,Number(e.executor_workers)||1))),Y(!!e.auto_retry_enabled),j(Math.max(0,Math.min(3,Number(e.max_auto_retries)||0))),te(e.retry_policy),se(Math.max(800,Math.min(12e3,Number(e.max_context_chars)||3500)))},tt=async e=>{l("loading");try{const t=await lt(e),i=t?.agent||o;et(i),l("ready"),u(t?.source==="saved"?`\u5DF2\u52A0\u8F7D\u9879\u76EE #${e} \u7684\u667A\u80FD\u4F53\u9ED8\u8BA4\u914D\u7F6E\u3002`:`\u9879\u76EE #${e} \u4F7F\u7528\u7CFB\u7EDF\u9ED8\u8BA4\u667A\u80FD\u4F53\u914D\u7F6E\u3002`)}catch(t){l("idle"),u(`\u8B66\u544A\uFF1A\u52A0\u8F7D\u9879\u76EE\u667A\u80FD\u4F53\u9ED8\u8BA4\u914D\u7F6E\u5931\u8D25\uFF1A${t instanceof Error?t.message:String(t)}`)}},nt=async(e,t)=>{l("saving");try{await dt(e,t),l("ready")}catch(i){l("idle"),u(`\u8B66\u544A\uFF1A\u4FDD\u5B58\u9879\u76EE\u667A\u80FD\u4F53\u9ED8\u8BA4\u914D\u7F6E\u5931\u8D25\uFF1A${i instanceof Error?i.message:String(i)}`)}};P(()=>{le(he)},[he]);const st=e=>{const t=y(e.test_generation),i=y(e.ui_automation),Re=y(e.api_automation),at=y(e.evaluation),rt=y(e.agents);ge(c(t.generated_cases)),pe(c(i.script)),de(c(i.execution_result)),me(c(Re.script)),ye(c(Re.execution_result)),_e(c(at.output)),fe(c(rt))},m=e=>{re(e.status),ie(e.id),ae(e.stage_states||b()),st(e.artifacts||{}),s(e.error_message||null)},g=async()=>{if(a){oe(!0);try{const e=await ct(a);He(Array.isArray(e.items)?e.items:[])}catch(e){s(e instanceof Error?e.message:String(e))}finally{oe(!1)}}},p=async(e=r)=>{if(!e){f([]);return}ce(!0);try{const t=await ut(e);f(Array.isArray(t.items)?t.items:[]),v(null)}catch(t){s(t instanceof Error?t.message:String(t))}finally{ce(!1)}};return P(()=>{if(!a){f([]),l("idle");return}g(),tt(a)},[a]),P(()=>{if(!r||!h)return;const e=window.setInterval(async()=>{try{const t=await xe(r);m(t.run),p(t.run.id),t.run.status!=="running"&&t.run.status!=="pending"&&(u(`\u6D41\u6C34\u7EBF\u8FD0\u884C #${t.run.id} \u5DF2\u7ED3\u675F\uFF0C\u72B6\u6001\uFF1A${it[t.run.status]||t.run.status}\u3002`),g())}catch(t){s(t instanceof Error?t.message:String(t))}},2500);return()=>window.clearInterval(e)},[r,h]),{requirement:_,setRequirement:ve,expectedCount:w,setExpectedCount:Pe,compress:E,setCompress:Se,uiTask:T,setUiTask:be,uiTarget:M,setUiTarget:we,uiAutomationType:C,setUiAutomationType:Ee,apiRequirement:k,setApiRequirement:Te,apiBaseUrl:U,setApiBaseUrl:Me,apiPath:B,setApiPath:Ce,apiMode:O,setApiMode:ke,apiTestTypes:$,runTestcaseEval:L,setRunTestcaseEval:Be,runUiEval:D,setRunUiEval:Oe,runApiEval:N,setRunApiEval:$e,baselineTestCases:q,setBaselineTestCases:Le,agentEnabled:H,setAgentEnabled:F,agentPlannerLLM:K,setAgentPlannerLLM:W,agentReviewerLLM:V,setAgentReviewerLLM:G,agentExecutorParallel:z,setAgentExecutorParallel:I,agentExecutorWorkers:J,setAgentExecutorWorkers:Q,agentAutoRetryEnabled:X,setAgentAutoRetryEnabled:Y,agentMaxAutoRetries:Z,setAgentMaxAutoRetries:j,agentRetryPolicy:ee,setAgentRetryPolicy:te,agentMaxContextChars:ne,setAgentMaxContextChars:se,agentDefaultsState:De,errorMsg:Ne,stages:d,runStatus:R,activeRunId:r,history:qe,historyLoading:Fe,retryFromStage:ue,setRetryFromStage:le,traceLoading:Ke,traces:A,selectedTraceId:x,setSelectedTraceId:v,selectedTrace:Ze,generatedCases:We,uiScript:Ve,uiExecutionResult:Ge,apiScript:ze,apiExecutionResult:Ie,evaluationOutput:Je,agentInsights:Qe,isRunning:h,canRun:Xe,stageRows:Ye,toggleApiType:e=>{Ue(t=>t.includes(e)?t.filter(i=>i!==e):[...t,e])},runPipeline:async()=>{if(!a){s("\u8BF7\u5148\u9009\u62E9\u9879\u76EE\u3002");return}if(!_.trim()){s("\u8BF7\u8F93\u5165\u9700\u6C42\u8BF4\u660E\u3002");return}s(null);const e=je();await nt(a,e),u("\u5DF2\u542F\u52A8\u5168\u5C40\u7F16\u6392\u6D41\u6C34\u7EBF\uFF08\u6301\u4E45\u5316\u8FD0\u884C\uFF09\u3002");try{const t=await ot({project_id:a,requirement:_,expected_count:w,compress:E,ui:{task:T,target:M,automation_type:C},api:{requirement:k,base_url:U,api_path:B,mode:O,test_types:$},evaluation:{run_testcase_eval:L,run_ui_eval:D,run_api_eval:N,baseline_test_cases:q},agent:e});m(t.run),g(),p(t.run.id)}catch(t){s(t instanceof Error?t.message:String(t))}},resetView:()=>{ae(b()),re("idle"),ie(null),s(null),ge(""),pe(""),de(""),me(""),ye(""),_e(""),fe(""),f([]),v(null)},resumeRun:async()=>{if(r){s(null);try{const e=await gt(r);m(e.run),u(e.message||`\u5DF2\u6062\u590D\u8FD0\u884C #${r}\u3002`),g(),p(e.run.id)}catch(e){s(e instanceof Error?e.message:String(e))}}},retryRun:async()=>{if(r){s(null);try{const e=await pt(r,ue);m(e.run),u(e.message||`\u5DF2\u4ECE\u8FD0\u884C #${r} \u521B\u5EFA\u91CD\u8BD5\u4EFB\u52A1\u3002`),g(),p(e.run.id)}catch(e){s(e instanceof Error?e.message:String(e))}}},refreshHistory:g,refreshTraces:p,openHistoryRun:async e=>{try{const t=await xe(e);m(t.run),u(`\u5DF2\u52A0\u8F7D\u6D41\u6C34\u7EBF\u8FD0\u884C #${e}\u3002`),p(t.run.id)}catch(t){s(t instanceof Error?t.message:String(t))}}}}export{Pt as __runtimeUsePipelineOrchestrationController};

import type { PipelineRunStatus, StageKey, StageStatus, WorkflowTraceItem, PipelineRun } from './model';

type StageRow = { key: StageKey; status: StageStatus; message: string };

type PipelineControllerShape = {
  requirement: string;
  setRequirement: (value: string) => void;
  expectedCount: number;
  setExpectedCount: (value: number) => void;
  compress: boolean;
  setCompress: (value: boolean) => void;
  uiTask: string;
  setUiTask: (value: string) => void;
  uiTarget: string;
  setUiTarget: (value: string) => void;
  uiAutomationType: "web" | "app";
  setUiAutomationType: (value: "web" | "app") => void;
  apiRequirement: string;
  setApiRequirement: (value: string) => void;
  apiBaseUrl: string;
  setApiBaseUrl: (value: string) => void;
  apiPath: string;
  setApiPath: (value: string) => void;
  apiMode: "structured" | "natural";
  setApiMode: (value: "structured" | "natural") => void;
  apiTestTypes: string[];
  toggleApiType: (value: string) => void;
  runTestcaseEval: boolean;
  setRunTestcaseEval: (value: boolean) => void;
  runUiEval: boolean;
  setRunUiEval: (value: boolean) => void;
  runApiEval: boolean;
  setRunApiEval: (value: boolean) => void;
  baselineTestCases: string;
  setBaselineTestCases: (value: string) => void;
  agentDefaultsState: string;
  agentEnabled: boolean;
  setAgentEnabled: (value: boolean) => void;
  agentPlannerLLM: boolean;
  setAgentPlannerLLM: (value: boolean) => void;
  agentReviewerLLM: boolean;
  setAgentReviewerLLM: (value: boolean) => void;
  agentExecutorParallel: boolean;
  setAgentExecutorParallel: (value: boolean) => void;
  agentAutoRetryEnabled: boolean;
  setAgentAutoRetryEnabled: (value: boolean) => void;
  agentMaxContextChars: number;
  setAgentMaxContextChars: (value: number) => void;
  agentExecutorWorkers: number;
  setAgentExecutorWorkers: (value: number) => void;
  agentMaxAutoRetries: number;
  setAgentMaxAutoRetries: (value: number) => void;
  agentRetryPolicy: string;
  setAgentRetryPolicy: (value: 'conservative' | 'balanced' | 'aggressive') => void;
  errorMsg: string | null;
  runStatus: PipelineRunStatus;
  activeRunId: number | null;
  historyLoading: boolean;
  history: PipelineRun[];
  stageRows: StageRow[];
  retryFromStage: StageKey;
  setRetryFromStage: (value: StageKey) => void;
  traceLoading: boolean;
  traces: WorkflowTraceItem[];
  selectedTraceId: number | null;
  setSelectedTraceId: (value: number | null) => void;
  selectedTrace: WorkflowTraceItem | null;
  generatedCases: string;
  uiScript: string;
  uiExecutionResult: string;
  apiScript: string;
  apiExecutionResult: string;
  evaluationOutput: string;
  agentInsights: string;
  isRunning: boolean;
  canRun: boolean;
  runPipeline: () => Promise<void>;
  resetView: () => void;
  resumeRun: () => Promise<void>;
  retryRun: () => Promise<void>;
  refreshHistory: () => Promise<void>;
  refreshTraces: (runId?: number | null) => Promise<void>;
  openHistoryRun: (runId: number) => Promise<void>;
};

export type PipelineOrchestrationController = PipelineControllerShape;

export const usePipelineOrchestrationController = Pt as unknown as (args: { projectId: number | null; onLog: (msg: string) => void }) => PipelineControllerShape;
